export const STANDARD_UNITS = ['g', 'kg', 'mL', 'L', 'oz', 'fl oz', 'lb', 'pt', 'qt', 'gal', 'tsp', 'tbsp', 'cup', 'ea'] as const

const UNIT_ALIASES: Record<string, string> = {
  g: 'g',
  gr: 'g',
  gm: 'g',
  gram: 'g',
  grams: 'g',
  gramme: 'g',
  grammes: 'g',
  kg: 'kg',
  kilogram: 'kg',
  kilograms: 'kg',
  kilogramme: 'kg',
  kilogrammes: 'kg',
  ml: 'mL',
  milliliter: 'mL',
  milliliters: 'mL',
  millilitre: 'mL',
  millilitres: 'mL',
  l: 'L',
  liter: 'L',
  liters: 'L',
  litre: 'L',
  litres: 'L',
  oz: 'oz',
  ounce: 'oz',
  ounces: 'oz',
  'fl oz': 'fl oz',
  floz: 'fl oz',
  'fluid ounce': 'fl oz',
  'fluid ounces': 'fl oz',
  lb: 'lb',
  lbs: 'lb',
  pound: 'lb',
  pounds: 'lb',
  pt: 'pt',
  pts: 'pt',
  pint: 'pt',
  pints: 'pt',
  qt: 'qt',
  qts: 'qt',
  quart: 'qt',
  quarts: 'qt',
  gal: 'gal',
  gals: 'gal',
  gallon: 'gal',
  gallons: 'gal',
  tsp: 'tsp',
  teaspoon: 'tsp',
  teaspoons: 'tsp',
  tbsp: 'tbsp',
  tablespoon: 'tbsp',
  tablespoons: 'tbsp',
  cup: 'cup',
  cups: 'cup',
  ea: 'ea',
  each: 'ea',
  unit: 'ea',
  units: 'ea',
  count: 'ea',
  ct: 'ea',
  piece: 'ea',
  pieces: 'ea',
  pc: 'ea'
}

export function normalizeUnit(value: unknown): string | null {
  const unit = String(value ?? '').trim()
  if (!unit) return null
  const key = unit.toLowerCase().replaceAll('.', '').replace(/\s+/g, ' ')
  return UNIT_ALIASES[key] ?? unit
}
